### ISSUE TITLE
Add function names in combinatorics

### ISSUE THREAD

**Issue by MAG-BOSS** [fermulerpy/fermulerpy#16]
Go to src >> fermulerpy >> combinatorics >> init.py

Complete it in same way as has been done in src >> fermulerpy >> elementary >> init.py

**Comment by Tushar-Sharma007** [comment]
I want to solve this issue, will you assign it to me

**Comment by MAG-BOSS** [comment]
Go ahead @Tushar-Sharma007 , if you face any problem you can ask here
