### ISSUE TITLE
Tests for contant module

### ISSUE THREAD

**Issue by MAG-BOSS** [fermulerpy/fermulerpy#95]
As of now, tests for constant modules have not been added. They can be added in tests >> test_constants. In the test_constants directory rename the file f.py to test_useful_series.py
 Then add at least 4 tests for each function present in src>>fermulerpy>>constants>>useful_series.py
You can take help from the tests implemented in test>>test_elementary directory.

**Comment by sumit-158** [comment]
can i work on this?

**Comment by MAG-BOSS** [comment]
@sumit-158 Go ahead !
While adding tests, carefully follow the same coding style. Also, verify your answer from trusted sources (or check them with brute force). Don't forget to add a test for checking edge or corner cases. Feel free to ask any question

**Comment by sumit-158** [comment]
@MAG-BOSS I had renamed file f.py but I am confuse for other task please help me out!

**Comment by sumit-158** [comment]
I have completed my work, can you help how to make PR.

**Comment by MAG-BOSS** [comment]
@sumit-158 , follow the steps given here :[ LINK](https://github.com/firstcontributions/first-contributions) . You will find answers for most of your queries here.

**Comment by sumit-158** [comment]
sorry to bother you again, but i got stuck here, the modified file is not adding to staging area can you please help me out!!

$ git status
On branch dev
Your branch is up to date with 'origin/dev'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   fermulerpy (modified content, untracked content)

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by sumit-158** [comment]
@MAG-BOSS I had successfully push and passed the test, thanks for guiding me through out the whole process!
